"""`vigil hook` — pre-write gate as a git pre-commit hook.

`vigil hook install <memory_dir>` writes a pre-commit hook that runs
`vigil hook run <memory_dir>` over staged/changed *.md files. The hook BLOCKS the
commit (nonzero exit) on CRITICAL pre-write contradictions and WARNS (exit 0) on
WARNING-level conflicts.

Install target:
  - If the memory dir is inside a git repo, the hook is written to that repo's
    `.git/hooks/pre-commit` (chained if one already exists).
  - Otherwise a standalone script is written to `<memory_dir>/.vigil/pre-commit`
    that you can wire up yourself.

`vigil hook run <memory_dir>` is the hook body: it pre-write-checks the staged
markdown (or, outside git, all *.md) and exits nonzero on any CRITICAL.
"""

from __future__ import annotations

import os
import stat
import subprocess
import sys
from pathlib import Path


def _git_repo_root(start: Path) -> Path | None:
    """Return the git repo root containing `start`, or None."""
    try:
        out = subprocess.run(
            ['git', '-C', str(start), 'rev-parse', '--show-toplevel'],
            capture_output=True, text=True, check=True)
        return Path(out.stdout.strip())
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


HOOK_TEMPLATE = """#!/bin/sh
# Vigil pre-commit gate — blocks commits that introduce CRITICAL memory
# contradictions. Generated by `vigil hook install`. Edit MEMORY_DIR if you
# move the memory directory.
MEMORY_DIR="{memory_dir}"
exec {python} -m vigil hook run "$MEMORY_DIR"
"""


def _hook_body(memory_dir: Path) -> str:
    python = sys.executable or 'python3'
    return HOOK_TEMPLATE.format(memory_dir=str(memory_dir), python=python)


def _make_executable(path: Path) -> None:
    st = path.stat().st_mode
    path.chmod(st | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)


def install_hook(memory_dir: Path) -> dict:
    """Install the pre-commit hook. Returns {path, mode, chained}.

    mode is 'git' (written into .git/hooks) or 'standalone' (<memory_dir>/.vigil).
    """
    memory_dir = Path(memory_dir).resolve()
    repo = _git_repo_root(memory_dir)
    body = _hook_body(memory_dir)

    if repo is not None:
        hooks_dir = repo / '.git' / 'hooks'
        hooks_dir.mkdir(parents=True, exist_ok=True)
        hook_path = hooks_dir / 'pre-commit'
        chained = False
        if hook_path.exists():
            existing = hook_path.read_text(encoding='utf-8', errors='replace')
            if 'vigil hook run' in existing or 'vigil.hook' in existing or '-m vigil hook' in existing:
                # already installed — overwrite to refresh path
                hook_path.write_text(body, encoding='utf-8')
            else:
                # chain: append a call so we don't clobber an existing hook
                runner_path = hooks_dir / 'pre-commit-vigil'
                runner_path.write_text(body, encoding='utf-8')
                _make_executable(runner_path)
                if not existing.endswith('\n'):
                    existing += '\n'
                existing += f'\n# Vigil gate\n"{runner_path}" || exit $?\n'
                hook_path.write_text(existing, encoding='utf-8')
                _make_executable(hook_path)
                chained = True
                return {'path': str(runner_path), 'mode': 'git', 'chained': True,
                        'pre_commit': str(hook_path)}
        else:
            hook_path.write_text(body, encoding='utf-8')
        _make_executable(hook_path)
        return {'path': str(hook_path), 'mode': 'git', 'chained': chained}

    # standalone
    vigil_dir = memory_dir / '.vigil'
    vigil_dir.mkdir(parents=True, exist_ok=True)
    hook_path = vigil_dir / 'pre-commit'
    hook_path.write_text(body, encoding='utf-8')
    _make_executable(hook_path)
    return {'path': str(hook_path), 'mode': 'standalone', 'chained': False}


def _staged_markdown(memory_dir: Path) -> list[Path]:
    """Staged *.md files under memory_dir (via git), else all *.md in the dir."""
    repo = _git_repo_root(memory_dir)
    if repo is None:
        return sorted(memory_dir.glob('*.md'))
    try:
        out = subprocess.run(
            ['git', '-C', str(repo), 'diff', '--cached', '--name-only',
             '--diff-filter=ACM'],
            capture_output=True, text=True, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        return sorted(memory_dir.glob('*.md'))

    files = []
    md = Path(memory_dir).resolve()
    for name in out.stdout.splitlines():
        name = name.strip()
        if not name.endswith('.md'):
            continue
        p = (repo / name).resolve()
        try:
            p.relative_to(md)
        except ValueError:
            continue
        if p.exists():
            files.append(p)
    return files


def run_hook(
    memory_dir: Path,
    store_dir: Path | None = None,
    collection_name: str | None = None,
    out=None,
) -> int:
    """Run the gate. Returns an exit code: nonzero on any CRITICAL conflict.

    Uses the daemon if one is running (fast), else an in-process pre-write check.
    """
    out = out or sys.stderr
    from .indexer import default_store_dir
    from .scanner import pre_write_check
    from . import daemon

    memory_dir = Path(memory_dir)
    if store_dir is None:
        store_dir = default_store_dir(memory_dir)

    files = _staged_markdown(memory_dir)
    if not files:
        return 0

    n_critical = 0
    n_warning = 0
    use_daemon = daemon.daemon_running(store_dir)

    for f in files:
        text = f.read_text(encoding='utf-8', errors='replace')
        issues = None
        if use_daemon:
            resp = daemon.check_via_daemon(
                store_dir, text, source=f.stem, collection_name=collection_name)
            if resp and resp.get('ok'):
                issues = resp['conflicts']
        if issues is None:
            raw = pre_write_check(text, store_dir=store_dir, source_file=f.stem,
                                  collection_name=collection_name)
            issues = [{'severity': i.severity, 'category': i.category,
                       'message': i.message, 'files': i.files} for i in raw]

        for iss in issues:
            if iss.get('category') not in ('pre_write_conflict',):
                continue
            if iss['severity'] == 'CRITICAL':
                n_critical += 1
                print(f'  [!!!] {f.name}: {iss["message"]}', file=out)
            elif iss['severity'] == 'WARNING':
                n_warning += 1
                print(f'  [ ! ] {f.name}: {iss["message"]}', file=out)

    if n_critical:
        print(f'\nVigil: BLOCKED — {n_critical} CRITICAL contradiction(s)'
              f' in staged memory. Resolve or `git commit --no-verify` to override.',
              file=out)
        return 1
    if n_warning:
        print(f'\nVigil: {n_warning} WARNING contradiction(s) — commit allowed.',
              file=out)
    return 0
